### ISSUE TITLE
Suggestion for improvement - shortcut first request if it is getting too much data

### ISSUE THREAD

**Issue by jmtcsngr** [jeromekelleher/htsget#24]
If the first request (the one which is expecting to get a json back) goes for a crazy big file. Say you point it by accident to a big sam/bam file. The client will try to download the huge file and then parse it as json and likely fail. So probably better to do something like check headers and see if it is a json, then stream content or use streaming request and kill if the response is bigger than a reasonable limit. Is unlikely you will want to parse a 100 megabyte file anyway.

**Comment by jeromekelleher** [comment]
Excellent idea. I'll code something up soon and ping you for comments.
